name: basic-text-output
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu:latest
    steps:
      - name: Printing greeting
        run: echo "Hola Jose"
      - name: Printing good-bye
        run: echo "Good bye Jose"
